"""empty message

Revision ID: 99058abe1a38
Revises: cb1dd378843e
Create Date: 2019-09-17 16:20:29.675514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99058abe1a38'
down_revision = 'cb1dd378843e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wpm', sa.String(), nullable=True),
    sa.Column('time', sa.String(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scores')
    # ### end Alembic commands ###
